# image: https://hub.docker.com/r/aapanel/aapanel


version: '3.8'

services:
  aapanel:
    image: aapanel/aapanel:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - '${APP_FTP_PORT}:21'
      - '${APP_SSH_PORT}:22'
      - '${APP_PORT}:8888'
      - '${APP_PHPMYADMIN_PORT}:888'
    environment:
      - BT_USER=$APP_USER
      - BT_PASSWORD=$APP_PASSWORD
    volumes:
      - 'aapanel:/www'
      
networks:
  default:
      name: ${APP_NAME}

volumes:
  aapanel: