# English image: https://hub.docker.com/r/aapanel/aapanel
# Chinese image: https://hub.docker.com/r/btpanel/btpanel
# English image not have /bt.sh script, so cat from Chinese image and add it to command


version: '3.8'

services:
  aapanel:
    image: aapanel/aapanel:${APP_VERSION}
    container_name: ${APP_NAME}
    labels:
      - "editon=English"
    ports:
      - '${APP_FTP_PORT}:21'
      - '${APP_SSH_PORT}:22'
      - '${APP_PORT}:8888'
      - '${APP_PHPMYADMIN_PORT}:888'
    environment:
      - BAOTA_USER=$APP_USER
      - BAOTA_PASSWORD=$APP_PASSWORD
    volumes:
      - 'www:/www'
    command: bash -c "cat /my_cmd > cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd
    profiles:
      - en

  baotao:
    image: btpanel/baota:${APP_VERSION}
    container_name: ${APP_NAME}
    labels:
      - "editon=Chinese"
    ports:
      - '${APP_FTP_PORT}:21'
      - '${APP_SSH_PORT}:22'
      - '${APP_PORT}:8888'
      - '${APP_PHPMYADMIN_PORT}:888'
    command: bash -c "cat /my_cmd > cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    configs:
      - source: my_cmd
    environment:
      - BAOTA_USER=$APP_USER
      - BAOTA_PASSWORD=$APP_PASSWORD
    volumes:
      - 'www:/www'
    profiles:
      - cn

networks:
  default:
      name: ${APP_NAME}

volumes:
  www:

configs:
  my_cmd:
    file: ./cmd.sh